<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="helpers.jspf"%>
<%String base=request.getContextPath(),clase=(String)request.getAttribute("claseContacto");Usuario persona=(Usuario)request.getAttribute("personaContacto");Contacto c=(Contacto)request.getAttribute("contactoEditando");List<Contacto> contactos=(List<Contacto>)request.getAttribute("contactos");List<String[]> distritos=(List<String[]>)request.getAttribute("distritos");Object token=session.getAttribute("csrf");%>
<div class="page-heading"><div><span class="eyebrow">DATOS PERSONALES</span><h1>Contactos y direcciones</h1><p class="muted"><%=esc(persona.username)%> · <%=esc(persona.nombres)%> <%=esc(persona.apellidos)%></p></div><a class="button secondary" href="<%=base%>/usuarios?editar=<%=persona.id%>">Volver al usuario</a></div>
<nav class="contact-tabs" aria-label="Tipos de contacto"><%String[] tipos={"correo","telefono","direccion"},titulos={"Correos","Teléfonos","Direcciones"};for(int i=0;i<tipos.length;i++){%><a class="button <%=clase.equals(tipos[i])?"":"secondary"%>" href="<%=base%>/contactos?usuarioId=<%=persona.id%>&amp;clase=<%=tipos[i]%>"><%=titulos[i]%></a><%}%></nav>
<form class="card editor" method="post" action="<%=base%>/contactos"><input type="hidden" name="csrf" value="<%=esc(token)%>"><input type="hidden" name="usuarioId" value="<%=persona.id%>"><input type="hidden" name="clase" value="<%=clase%>"><input type="hidden" name="id" value="<%=c.id%>"><input type="hidden" name="accion" value="guardar"><h2><%=c.id==0?"Agregar contacto":"Editar contacto"%></h2><div class="form-grid">
<%=campo("correo".equals(clase)?"Correo electrónico":"telefono".equals(clase)?"Número de teléfono":"Calle o avenida","valor",c.valor,"correo".equals(clase)?"email":"telefono".equals(clase)?"tel":"text","correo".equals(clase)?80:"telefono".equals(clase)?20:150,true)%>
<%=campo("Tipo (personal, laboral, domicilio…)","tipo",c.tipo,"text",20,true)%>
<%if("direccion".equals(clase)){%>
<label>Distrito<select name="distrito" required><option value="">Selecciona una ubicación</option><%boolean encontrado=false;for(String[] d:distritos){boolean elegido=c.distritoId==Integer.parseInt(d[0]);encontrado|=elegido;%><option value="<%=esc(d[0])%>" <%=elegido?"selected":""%>><%=esc(d[1])%></option><%}if(c.distritoId>0&&!encontrado){%><option value="<%=c.distritoId%>" selected>Ubicación inactiva: selecciona otra</option><%}%></select></label>
<%=campo("Número (opcional)","numero",c.numero,"text",10,false)%><%=campo("Piso (opcional)","piso",c.piso,"text",10,false)%><%=campo("Referencia (opcional)","referencia",c.referencia,"text",255,false)%><%}%>
</div><label class="check"><input name="activo" type="checkbox" <%=c.activo?"checked":""%>>Contacto activo</label>
<%if("direccion".equals(clase)&&distritos.isEmpty()){%><p class="muted">Primero registra el país, departamento, provincia y distrito en <a href="<%=base%>/ubicaciones">Ubicaciones</a>.</p><%}%>
<div class="form-actions"><button>Guardar contacto</button><a href="<%=base%>/contactos?usuarioId=<%=persona.id%>&amp;clase=<%=clase%>">Limpiar formulario</a></div></form>
<section class="card"><h2>Contactos registrados</h2><div class="scroll"><table><thead><tr><th>Contacto</th><th>Tipo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
<%for(Contacto x:contactos){%><tr><td><%=esc(x.valor)%><%if("direccion".equals(clase)){%><small>N.º <%=esc(x.numero)%> · Piso <%=esc(x.piso)%></small><small><%boolean ubicado=false;for(String[] d:distritos)if(Integer.parseInt(d[0])==x.distritoId){ubicado=true;%><%=esc(d[1])%><%}if(!ubicado){%>Ubicación inactiva (ID <%=x.distritoId%>)<%}%></small><small><%=esc(x.referencia)%></small><%}%></td><td><%=esc(x.tipo)%></td><td><%=x.activo?"Activo":"Inactivo"%></td><td><a href="<%=base%>/contactos?usuarioId=<%=persona.id%>&amp;clase=<%=clase%>&amp;editar=<%=x.id%>">Editar</a><details><summary>Eliminar</summary><p>¿Eliminar este contacto?</p><form method="post" action="<%=base%>/contactos"><input type="hidden" name="csrf" value="<%=esc(token)%>"><input type="hidden" name="usuarioId" value="<%=persona.id%>"><input type="hidden" name="clase" value="<%=clase%>"><input type="hidden" name="id" value="<%=x.id%>"><input type="hidden" name="accion" value="eliminar"><button class="secondary">Confirmar eliminación</button></form></details></td></tr><%}%>
<%if(contactos.isEmpty()){%><tr><td colspan="4">Este usuario todavía no tiene contactos de este tipo.</td></tr><%}%>
</tbody></table></div></section>
