<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="com.mycompany.novatech.app.comercial.*"%>
<%@include file="helpers.jspf"%>
<%String base=request.getContextPath();Map<String,String> f=(Map<String,String>)request.getAttribute("productoForm");List<Producto> lista=(List<Producto>)request.getAttribute("productos");Object token=session.getAttribute("csrf");%>
<div class="page-heading"><div><span class="eyebrow">CATÁLOGO COMERCIAL</span><h1>Productos y servicios</h1><p class="muted">Mantén códigos, clasificación, precios en soles y existencias.</p></div><a class="button" href="<%=base%>/productos?nuevo=1">＋ Nuevo artículo</a></div>
<p><a href="<%=base%>/catalogos-productos">Administrar categorías, marcas y unidades</a></p>
<%if(Boolean.TRUE.equals(request.getAttribute("mostrarForm"))){%><form class="card editor" method="post" action="<%=base%>/productos"><h2><%="0".equals(f.get("id"))?"Nuevo":"Editar"%> artículo</h2><input type="hidden" name="csrf" value="<%=esc(token)%>"><input type="hidden" name="id" value="<%=esc(f.get("id"))%>"><input type="hidden" name="accion" value="guardar"><div class="form-grid">
<%=campo("Código","codigo",f.get("codigo"),"text",40,true)%><%=campo("Nombre","nombre",f.get("nombre"),"text",150,true)%>
<label>Tipo<select name="tipo" required><%for(String tipo:new String[]{"PRODUCTO","SERVICIO","INSUMO"}){%><option <%=tipo.equals(f.get("tipo"))?"selected":""%>><%=tipo%></option><%}%></select></label>
<%String[] attrs={"categorias","marcas","unidades"},keys={"categoria","marca","unidad"},labels={"Categoría","Marca (opcional)","Unidad de medida"};for(int i=0;i<3;i++){%>
<label><%=labels[i]%><select name="<%=keys[i]%>" <%=i==1?"":"required"%>><option value="">Selecciona una opción</option><%for(String[] c:(List<String[]>)request.getAttribute(attrs[i])){%><option value="<%=esc(c[0])%>" <%=c[0].equals(f.get(keys[i]))?"selected":""%>><%=esc(c[1])%><%="1".equals(c[2])?"":" · Inactivo"%></option><%}%></select></label><%}%>
<label>Proveedor principal (opcional)<select name="proveedor"><option value="">Sin proveedor</option><%for(Proveedor p:(List<Proveedor>)request.getAttribute("proveedoresProducto")){%><option value="<%=p.id%>" <%=String.valueOf(p.id).equals(f.get("proveedor"))?"selected":""%>><%=esc(p.razonSocial)%><%=p.activo?"":" · Inactivo"%></option><%}%></select></label>
<label>Precio (S/)<input name="precio" type="number" min="0" max="999999999.99" step="0.01" value="<%=esc(f.get("precio"))%>" required></label>
<label>Stock actual<input name="stock" type="number" min="0" max="999999999.99" step="0.001" value="<%=esc(f.get("stock"))%>" required></label>
<label>Stock mínimo<input name="minimo" type="number" min="0" max="999999999.99" step="0.001" value="<%=esc(f.get("minimo"))%>" required></label>
<label>Descripción<textarea name="descripcion" maxlength="500" rows="3"><%=esc(f.get("descripcion"))%></textarea></label></div>
<p class="muted">Los servicios no tienen existencias: stock y mínimo deben ser cero. Este formulario mantiene el stock actual; el registro de ventas se incorporará en la etapa 6.</p>
<label class="check"><input type="checkbox" name="activo" <%=!f.getOrDefault("activo","").isEmpty()?"checked":""%>>Artículo activo</label><div class="form-actions"><button>Guardar artículo</button><a href="<%=base%>/productos">Cancelar</a></div></form><%}%>
<form class="toolbar" method="get" action="<%=base%>/productos"><label>Buscar por código, nombre o tipo<input name="q" maxlength="100" value="<%=esc(request.getAttribute("busquedaComercial"))%>"></label><button>Buscar</button><a href="<%=base%>/productos">Ver todos</a></form>
<section class="card"><h2>Artículos registrados</h2><p class="muted">Hasta 500 resultados. Los avisos de stock no se aplican a servicios.</p><div class="scroll"><table><thead><tr><th>Código / nombre</th><th>Tipo</th><th>Precio (S/)</th><th>Stock / mínimo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
<%for(Producto p:lista){%><tr><td><strong><%=esc(p.codigo)%></strong><div><%=esc(p.nombre)%></div></td><td><%=esc(p.tipo)%></td><td><%=p.precio.toPlainString()%></td><td><%if("SERVICIO".equals(p.tipo)){%>No aplica<%}else{%><%=p.stock.toPlainString()%> / <%=p.stockMinimo.toPlainString()%><%if(p.stock.compareTo(p.stockMinimo)<=0){%><div>Stock bajo</div><%}}%></td><td><%=p.activo?"Activo":"Inactivo"%></td><td><a href="<%=base%>/productos?editar=<%=p.id%>">Editar</a><details><summary>Eliminar</summary><p>Solo si no tiene stock ni operaciones relacionadas. Puedes marcarlo como inactivo para conservarlo.</p><%=accion(base,token,p.id,"/productos","eliminar","Confirmar eliminación")%></details></td></tr><%}if(lista.isEmpty()){%><tr><td colspan="6">No hay artículos para esta búsqueda.</td></tr><%}%>
</tbody></table></div></section>
