<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="helpers.jspf"%>
<%String base=request.getContextPath(),nivel=(String)request.getAttribute("nivelUbicacion");List<String[]> lista=(List<String[]>)request.getAttribute("ubicaciones"),padres=(List<String[]>)request.getAttribute("padres");String[] u=(String[])request.getAttribute("ubicacionEditando");Object token=session.getAttribute("csrf");%>
<div class="page-heading"><div><span class="eyebrow">DATOS PERSONALES</span><h1>Ubicaciones</h1><p class="muted">Registra las ubicaciones que necesitas para las direcciones de usuarios.</p></div></div>
<nav class="contact-tabs" aria-label="Niveles de ubicación"><%String[] niveles={"pais","departamento","provincia","distrito"},titulos={"Países","Departamentos","Provincias","Distritos"};for(int i=0;i<niveles.length;i++){%><a class="button <%=nivel.equals(niveles[i])?"":"secondary"%>" href="<%=base%>/ubicaciones?nivel=<%=niveles[i]%>"><%=titulos[i]%></a><%}%></nav>
<form class="card editor" method="post" action="<%=base%>/ubicaciones"><input type="hidden" name="csrf" value="<%=esc(token)%>"><input type="hidden" name="nivel" value="<%=nivel%>"><input type="hidden" name="id" value="<%=esc(u[0])%>"><input type="hidden" name="accion" value="guardar"><h2><%="0".equals(u[0])?"Nueva ubicación":"Editar ubicación"%></h2><div class="form-grid"><%=campo("Nombre","nombre",u[1],"text",100,true)%>
<%if(!"pais".equals(nivel)){%><label>Ubicación superior<select name="padre" required><option value="">Selecciona una ubicación</option><%for(String[] p:padres){%><option value="<%=esc(p[0])%>" <%=p[0].equals(u[2])?"selected":""%>><%=esc(p[1])%><%="1".equals(p[3])?"":" · Inactiva"%></option><%}%></select></label><%}%>
</div><label class="check"><input type="checkbox" name="activo" <%="1".equals(u[3])?"checked":""%>>Ubicación activa</label><div class="form-actions"><button>Guardar ubicación</button><a href="<%=base%>/ubicaciones?nivel=<%=nivel%>">Limpiar formulario</a></div></form>
<section class="card"><h2>Ubicaciones registradas</h2><div class="scroll"><table><thead><tr><th>Nombre</th><th>Ubicación superior</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><%for(String[] r:lista){%><tr><td><%=esc(r[1])%></td><td><%for(String[] p:padres)if(p[0].equals(r[2])){%><%=esc(p[1])%><%}%></td><td><%="1".equals(r[3])?"Activo":"Inactivo"%></td><td><a href="<%=base%>/ubicaciones?nivel=<%=nivel%>&amp;editar=<%=esc(r[0])%>">Editar</a><details><summary>Eliminar</summary><p>Solo puede eliminarse si no tiene ubicaciones ni direcciones relacionadas.</p><form method="post" action="<%=base%>/ubicaciones"><input type="hidden" name="csrf" value="<%=esc(token)%>"><input type="hidden" name="nivel" value="<%=nivel%>"><input type="hidden" name="id" value="<%=esc(r[0])%>"><input type="hidden" name="accion" value="eliminar"><button class="secondary">Confirmar eliminación</button></form></details></td></tr><%}if(lista.isEmpty()){%><tr><td colspan="4">Todavía no hay ubicaciones registradas en este nivel.</td></tr><%}%></tbody></table></div></section>
